[package]
name = "fmtron"
version = "0.7.0"
authors = [
    "Anton Filippov <a.filippov@protonmail.com>",
    "Rafael Bachmann <rafael.bachmann.93@gmail.com>",
]
description = "A simple tool for autoformatting RON files."
homepage = "https://github.com/barafael/fmtron"
readme = "README.md"
keywords = ["RON", "autoformatting", "beautify", "pretty-print"]
categories = ["command-line-utilities", "development-tools", "value-formatting"]
license = "MIT"
repository = "https://github.com/barafael/fmtron"
edition = "2024"

[dependencies]
clap = { version = "4.6.7", features = ["derive"] }
pest = "2.9"
pest_derive = "2.9"
thiserror = "2"
unicode-width = "0.2"

[dev-dependencies]
fs-walk = "0.2"
ron = "0.12"
tempfile = "3.27.0"
